BTPecoliste/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path("", include("ecoliste.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
]

ecoliste/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = "ecoliste"
urlpatterns = [
    path(_(""), views.search_view, name="search"),
    path(
        _("entreprise/<int:enterprise_id>/"), views.enterprise_view, name="enterprise"
    ),
    path(_("about"), views.about_view, name="about"),
    path(_("legal"), views.about_view, name="legal"),
    path(_("contact"), views.about_view, name="contact"),
]

ecoliste/models.py
# We use the WGS84 spherical projection. It's easier to use, but performances might be impacted. It could be useful
# to change to a local projection. It would need to specify a projection setting, so it's easily changeable,
# and also to reproject the coordinates.

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _


class Enterprise(models.Model):
    """
    An enterprise and its identity.

    All the structure depends on this model, as everything links to it.
    """

    class Meta:
        verbose_name = _("Entreprise")
        verbose_name_plural = _("Entreprises")
        ordering = ["name"]

    class NEmployees(models.IntegerChoices):
        INDIVIDUAL = 1, "1"
        MICRO = 2, "2 - 9"
        SMALL = 10, "10 - 49"
        MEDIUM = 50, "50 - 249"
        MIDSIZE1 = 250, "250 - 999"
        MIDSIZE2 = 1000, "1000 - 4999"
        BIG = 5000, "5000+"

    class AnnualSales(models.IntegerChoices):
        MICRO = 1, _("< 2 millions €")
        SMALL = 2, _("2 à 10 millions €")
        MEDIUM = 3, _("10 à 50 millions €")
        INTERSIZE1 = 4, _("50 à 200 millions €")
        INTERSIZE2 = 5, _("200 à 1500 millions €")
        BIG = 6, _("> 1500 millions €")

    name = models.CharField(_("Nom"), max_length=200, null=False, db_index=True)
    website = models.URLField(
        _("Site web"),
        max_length=200,
        null=False,
        blank=True,
        db_index=True,
    )
    description = models.TextField(
        _("Description"), max_length=1000, null=False, blank=True
    )
    annual_sales = models.PositiveIntegerField(
        _("Chiffre d'affaires"),
        choices=AnnualSales.choices,
        null=True,
        blank=True,
        db_index=True,
    )
    n_employees = models.PositiveIntegerField(
        _("Nombre d'employés"),
        choices=NEmployees.choices,
        null=True,
        blank=True,
        db_index=True,
    )
    added = models.DateField(_("Date d'ajout"), auto_now_add=True)
    updated = models.DateField(_("Date de mise à jour"), auto_now=True)

    def __str__(self):
        return self.name


class Address(models.Model):
    """
    An address where an enterprise has a site.

    The site can be a production site, where materials are made.
    """

    class Meta:
        verbose_name = _("Adresse")
        verbose_name_plural = _("Adresses")

    enterprise = models.ForeignKey(
        Enterprise,
        on_delete=models.CASCADE,
        verbose_name=_("Entreprise"),
        related_name="addresses",
        db_index=True,
    )
    text_version = models.CharField(_("Adresse textuelle"), max_length=400, null=False)
    geolocation = models.PointField(
        _("Coordonnées"), geography=True, null=False, spatial_index=True
    )
    is_production = models.BooleanField(_("Est un lieu de production"))

    def __str__(self):
        return self.text_version


class MaterialTypeCategory(models.Model):
    """
    These categories are used to regroup Material Types.
    """

    class Meta:
        verbose_name = _("Catégorie de typologies")
        verbose_name_plural = _("Catégories de typologies")
        ordering = ["order"]

    name = models.CharField(
        _("Nom de la catégorie"), max_length=200, null=False, unique=True
    )
    order = models.PositiveSmallIntegerField(
        _("Ordre d'affichage"), null=False, default=99, db_index=True
    )

    def __str__(self):
        return self.name


class MaterialType(models.Model):
    """
    Defines the usages of the materials (insulation, beam...).
    """

    class Meta:
        verbose_name = _("Typologie de matériaux")
        verbose_name_plural = _("Typologies de matériaux")
        ordering = ["category", "order"]

    category = models.ForeignKey(
        MaterialTypeCategory,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_("Catégorie de typologie"),
        related_name="usages",
        db_index=True,
    )
    name = models.CharField(
        _("Typologie de matériaux"), max_length=200, null=False, unique=True
    )
    order = models.PositiveSmallIntegerField(
        _("Ordre d'affichage"), null=False, default=99, db_index=True
    )

    def __str__(self):
        return self.name


class BiobasedOriginMaterial(models.Model):
    """
    Based materials / origins for the biobased materials (wood, straw...).
    """

    class Meta:
        verbose_name = _("Matériau biosourcé")
        verbose_name_plural = _("Matériaux biosourcés")
        ordering = ["name"]

    name = models.CharField(
        _("Nom"), max_length=50, null=False, unique=True, db_index=True
    )

    def __str__(self):
        return self.name


class MaterialByEnterprise(models.Model):
    """
    A material produced by an enterprise.

    These materials have a type (for their usage), but also an origin. This last one defines why they are "ecological".
    """

    class Meta:
        verbose_name = _("Matériau produit")
        verbose_name_plural = _("Matériaux produits")
        ordering = ["type"]
        unique_together = [["enterprise", "type", "origin"]]

    class MaterialOrigins(models.IntegerChoices):
        REUSE = 1, _("De réemploi")
        BIOBASED = 2, _("Biosourcé")
        RECYCLED = 3, _("Recyclé")
        REUSABLE = 4, _("Réutilisable")

    enterprise = models.ForeignKey(
        Enterprise,
        on_delete=models.CASCADE,
        verbose_name=_("Entreprise"),
        related_name=_("products"),
        db_index=True,
    )
    type = models.ForeignKey(
        MaterialType,
        on_delete=models.CASCADE,
        verbose_name=_("Typologie"),
        related_name="products",
        db_index=True,
    )
    origin = models.PositiveSmallIntegerField(
        _("Origine"),
        choices=MaterialOrigins.choices,
        null=False,
    )
    address = models.ManyToManyField(
        Address,
        verbose_name=_("Adresse de production"),
        blank=True,
        related_name="products",
        db_index=True,
    )
    biobased_material = models.ManyToManyField(
        BiobasedOriginMaterial,
        verbose_name=_("Matériau biosourcé"),
        blank=True,
        related_name="products",
        db_index=True,
    )

    def __str__(self):
        return _("{type} {origin} produit par {enterprise}").format(
            type=self.type, origin=self.get_origin_display(), enterprise=self.enterprise
        )


class Contact(models.Model):
    class Meta:
        verbose_name = _("Contact")
        verbose_name_plural = _("Contacts")

    enterprise = models.ForeignKey(
        Enterprise,
        on_delete=models.CASCADE,
        verbose_name=_("Entreprise"),
        related_name="contacts",
        db_index=True,
    )
    firstname = models.CharField(_("Prénom"), max_length=50, null=False, db_index=True)
    surname = models.CharField(
        _("Nom de famille"), max_length=50, null=False, db_index=True, blank=True
    )
    description = models.TextField(_("Description"), max_length=200, blank=True)
    phone1 = models.CharField(
        _("Téléphone 1"), max_length=25, db_index=True, blank=True
    )
    phone2 = models.CharField(
        _("Téléphone 2"), max_length=25, db_index=True, blank=True
    )
    mail = models.EmailField(_("Adresse mail"), db_index=True, null=True, blank=True)

    def __str__(self):
        return _("{firstname} {surname}").format(
            firstname=self.firstname, surname=self.surname
        )

ecoliste/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpRequest, QueryDict
from django.core.serializers import serialize
from django.contrib.gis.measure import D
from django.contrib.gis.geos import Point
from .models import Enterprise, Address


def ecoliste_research(
    search_location: Point, distance: int, filters: dict = None
) -> list[Address]:
    """
    The search of addresses corresponding to the user desired parameters.

    :param search_location: A geolocation using a Point object from django.contrib.gis.geos
    :param distance: The distance around the search location, in kilometers
    :param filters: A dictionary containing all available parameters from the models: material types, origin, enterprise
    size… Some parameters (materials, origin, biobased), who can have multiple values at once, need to be organized
    through the form filters[key] = [list of values] even if there is only one value. There should not be empty values
    or [""] values coming from a QueryDict. Other parameters (nemployees, sales) are ranges, therefore they need their
    2 values to be passed as a tuple.
    :return: A list of Address objects.
    """
    addresses = Address.objects.filter(
        geolocation__distance_lte=(search_location, D(km=distance))
    )
    if filters:
        if "materials" in filters.keys():
            # This parameter needs to be passed as a list
            addresses = addresses.filter(
                enterprise__products__type_id__in=filters["materials"]
            )
        if "origin" in filters.keys():
            # This parameter needs to be passed as a list
            addresses = addresses.filter(
                enterprise__products__origin__in=filters["origin"]
            )
        if "biobased" in filters.keys():
            # This parameter needs to be passed as a list
            addresses = addresses.filter(
                enterprise__products__biobased_material__id__in=filters["biobased"]
            )
        if "nemployees" in filters.keys():
            # This parameter needs to be passed as a tuple
            addresses = addresses.filter(
                enterprise__n_employees__range=filters["nemployees"]
            )
        if "sales" in filters.keys():
            # This parameter needs to be passed as a tuple
            addresses = addresses.filter(
                enterprise__annual_sales__range=filters["sales"]
            )
    return addresses


def ecoliste_research_querydict(
    search_location: Point, search_distance: int, querydict: QueryDict
) -> list[Address]:
    """
    Transcripts the QueryDict to a Dict, removes empty values, and passes it the ecoliste_research function.
    :param search_location: A geolocation using a Point object from django.contrib.gis.geos
    :param search_distance: The distance around the search location, in kilometers
    :param querydict: The QueryDict object sent by the html form.
    :return: A list of Address objects.
    """
    # filters = {key: value for key, value in querydict.lists()}
    filters = {}
    for key, value in querydict.lists():
        if not value == "":
            filters[key] = value
    return ecoliste_research(search_location, search_distance, filters=filters)


def search_view(request: HttpRequest) -> HttpResponse:
    return render(request, "ecoliste/search.html")


def enterprise_view(request: HttpRequest, enterprise_id: int) -> HttpResponse:
    enterprise = get_object_or_404(Enterprise, pk=enterprise_id)
    addresses = enterprise.addresses.all()
    contacts = enterprise.contacts.all()

    materials = (
        enterprise.products.all()
        .select_related("type", "type__category")
        .prefetch_related("address", "biobased_material")
    )
    addresses_points = serialize(
        "geojson",
        addresses,
        geometry_field="geolocation",
        fields=("text_version", "is_production"),
    )

    context = {
        "enterprise": enterprise,
        "addresses": addresses,
        "materials": materials,
        "contacts": contacts,
        "addresses_points": addresses_points,
    }
    return render(request, "ecoliste/enterprise.html", context)


def about_view(request: HttpRequest) -> HttpResponse:
    return render(request, "ecoliste/about.html")

ecoliste/templates/ecoliste/enterprise/addresses.html
<section id="addresses" class="column-half">
    <h1>Adresses</h1>
    <ul class="addresses-list">
        {% for address in addresses %}
            <li>{% if address.is_production %}
                <span class="is-production">🏭</span>{% endif %}{{ address.text_version }}</li>
        {% empty %}
            <li>Aucune adresse connue</li>
        {% endfor %}
    </ul>
    <script type="application/json" id="addresses-points">
        {% autoescape off %}{{ addresses_points }}{% endautoescape %}</script>
    {% load static %}
    <script type="text/plain" id="industry-icon-address">
        {% autoescape off %}{% static "ecoliste/images/map-icon-industry.png" %}{% endautoescape %}</script>
    <div id="addresses-map"></div>
</section>

ecoliste/templates/ecoliste/enterprise/contacts.html
<section id="contacts" class="column-half">
    <h1>Contacts</h1>
    <ul class="contacts-list">
        {% for contact in contacts %}
            <li>
                <ul class="contacts-list">
                    <li class="names"><span>👤</span>{{ contact.firstname }} {{ contact.surname }}</li>
                    <li class="mail"><span>📧</span><a href="mailto:{{ contact.mail }}">{{ contact.mail }}</a></li>
                    {% if contact.phone1 or contact.phone1 %}
                        <li class="phone">
                            <span><span>📞</span>{{ contact.phone1 }}</span><span><span>📱</span>{{ contact.phone2 }}</span>
                        </li>
                    {% endif %}
                    <li class="description"><span>💬</span>{{ contact.description }}</li>
                </ul>
            </li>
        {% empty %}
            <li>Aucun contact renseigné</li>
        {% endfor %}
    </ul>
</section>

ecoliste/templates/ecoliste/enterprise/identity.html
<section id="identity" class="column-half">
    <h1>Fiche d'identité</h1>
    <ul>
        {# Just so I remember : autoformatting might add carriage returns / spaces which then can fail the tests for empty enterprise #}
        <li>Nom : {{ enterprise.name }}</li>
        <li>Site internet : {% if enterprise.website %}
            <a href="{{ enterprise.website }}">{{ enterprise.website }}</a>{% else %}Aucun site web indiqué{% endif %}
        </li>
        <li>Description :
            {% if enterprise.description %}{{ enterprise.description }}{% else %}Pas de description{% endif %}</li>
        <li>Chiffre d'affaires :
            {% if enterprise.annual_sales %}{{ enterprise.get_annual_sales_display }}{% else %}
                Chiffre d'affaires inconnu
            {% endif %}</li>
        <li>Nombre d'employés :
            {% if enterprise.n_employees %}{{ enterprise.get_n_employees_display }}{% else %}
                Nombre d'employés inconnu
            {% endif %}</li>
        <li>Créée : {{ enterprise.added }}</li>
        <li>Modifiée : {{ enterprise.updated }}</li>
    </ul>
</section>

ecoliste/templates/ecoliste/enterprise/materials.html
<section id="materials" class="column-half">
    <h1>Matériaux</h1>

    {% regroup materials by type.category as category_list %}
    <ul class="materials-list">
        {% for category in category_list %}
            <li>
                <details>
                    <summary>{{ category.grouper }}</summary>
                    <ul class="materials-types">
                        {% regroup category.list by type as type_list %}
                        {% for type in type_list %}
                            <li>
                                <details>
                                    <summary>{{ type.grouper }}</summary>
                                    <ul class="materials-orgins">
                                        {% for material in type.list %}
                                            <li>{{ material.get_origin_display }}<span
                                                    class="is-production">🏭</span>
                                                <ul class="materials-addresses">
                                                    {% for address in material.address.all %}
                                                        <li>{{ address }}</li>
                                                    {% endfor %}
                                                </ul>
                                                {% if material.origin == 2 %}
                                                    <ul class="materials-biobased">
                                                        {% for biobased in material.biobased_material.all %}
                                                            <li>{{ biobased.name }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </details>
                            </li>
                        {% endfor %}
                    </ul>
                </details>
            </li>
        {% endfor %}
    </ul>

</section>